### ISSUE TITLE
Incorrect description for Red Cross & Clipboard

### ISSUE THREAD

**Issue by ShyrenMore** [HarshKapadia2/preview-markdown#11]
![image](https://user-images.githubusercontent.com/56788568/122071650-8b7fac00-ce14-11eb-9a7c-4ebd68ac8910.png)
As per the website functionality:
Red cross ('X'): Clear all the Markdown.
Clipboard: Copy all the Markdown in the input box.

**Comment by HarshKapadia2** [comment]
Oops! Thank you for pointing that out, Shyren!
You can make a PR to fix it if you want to! Please let me know.
You need just need to change the text in [`./src/util/initialText.js`](https://github.com/HarshKapadia2/preview-markdown/blob/main/src/util/initialText.js)
