### ISSUE TITLE
Add `kbd` tag styling.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/preview-markdown#17]
- The `kbd` tag is used to represent keyboard keys.
- Syntax: `<kbd>Ctrl</kbd> + <kbd>C</kbd>` -> <kbd>Ctrl</kbd> + <kbd>C</kbd>
- Add light and dark theme styling for this tag. (Replicate GitHub's 'Default light' and 'Default dark' themes.)
- CSS file: [`./src/css/output.css`](../blob/main/src/css/output.css)

**Comment by KartikSoneji** [comment]
On it.
