### ISSUE TITLE
Add 'Copied!' confirmation pop up.

### ISSUE THREAD

**Issue by HarshKapadia2** [HarshKapadia2/preview-markdown#2]
- Add a small message ('Copied!') above the copy button on clicking it.
- The message should disappear in a second or two.

![image](https://user-images.githubusercontent.com/50140864/121805936-22a90000-cc6b-11eb-9ecc-7bfdc8f334c2.png)

(Display 'Copied!' instead of 'Copy file to the clipboard'.)

**Comment by cod500** [comment]
This project is awesome. Do you mind if I help on this issue?

**Comment by HarshKapadia2** [comment]
Thank you so much!
No I don't mind. Go ahead and open a PR!
(Please read the [`CONTRIBUTING.md`](https://github.com/HarshKapadia2/preview-markdown/blob/main/CONTRIBUTING.md) file before doing anything.)

**Comment by HarshKapadia2** [comment]
Any updates, @cod500?

**Comment by HarshKapadia2** [comment]
Are you working on this issue, @cod500?

**Comment by cod500** [comment]
Yes, sorry for not getting back. I am working on it.

**Comment by cod500** [comment]
I just made a pull request. I tried to keep the popup exactly like what is showed in the image above and used prettier.

**Comment by HarshKapadia2** [comment]
Thank you for PR #15, but you seem to have closed it.
What happened?

**Comment by cod500** [comment]
I noticed it rewrote the json file so i wanted to do it again and not commit the json file. It showed 22,000 changes. I'm not sure what that's all about.

**Comment by HarshKapadia2** [comment]
Aah okay.
Also make sure you don't remove the new lines at the end of the files (check if Prettier is removing the lines by default).

**Comment by HarshKapadia2** [comment]
For the popup, use the dark theme font colour for the font colour, the dark theme table border colour for the border, and the dark theme background colour for the background colour.

If this is not looking good, then feel free to make it look good in whatever way you can. I would prefer staying within the colours already used in the project.

**Comment by cod500** [comment]
Used the dark theme. I fixed the new line save issue. They persisted this time.

**Comment by cod500** [comment]
I implemented useRef. Can I ask why the other queryselector method was used for clearBtn and such?

**Comment by HarshKapadia2** [comment]
Hey @cod500 sorry for the delay. There is a CI/CD issue going on with this repo and once I resolve that, I will be looking into your PR #16 and answering your questions. Sorry!

**Comment by HarshKapadia2** [comment]
> I implemented useRef.

Thank you!

> Can I ask why the other queryselector method was used for clearBtn and such?

I was struggling with `useRef` and didn't have time initially. I know I increased the Technical Debt of the project by using `querySelector`, but I'll correct it now.

**Comment by HarshKapadia2** [comment]
Implemented in PR #19.
